# Generated by Django 5.0 on 2025-11-12 17:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=19)),
                ('affiliation', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'unique_together': {('given_name', 'family_name')},
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('doi', models.CharField(blank=True, db_index=True, max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('paper_type', models.CharField(default='article', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers/pdfs/%Y/%m/')),
                ('full_text', models.TextField(blank=True)),
                ('full_text_hash', models.CharField(blank=True, max_length=64)),
                ('summary_overview', models.TextField(blank=True)),
                ('summary_methods', models.TextField(blank=True)),
                ('summary_findings', models.TextField(blank=True)),
                ('summary_significance', models.TextField(blank=True)),
                ('keywords_ai', models.JSONField(default=list)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reading_status', models.CharField(choices=[('to_read', 'To Read'), ('reading', 'Reading'), ('read', 'Read'), ('reference', 'Reference')], default='to_read', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('citation_count', models.IntegerField(default=0)),
                ('is_open_access', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='papers.paper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(default='#3B82F6', max_length=7)),
                ('papers', models.ManyToManyField(blank=True, related_name='tags', to='papers.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['user', 'reading_status'], name='papers_pape_user_id_09e1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['user', 'created_at'], name='papers_pape_user_id_0063c3_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['doi'], name='papers_pape_doi_905538_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='papers_pape_search__9e4ff7_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='paperauthor',
            unique_together={('paper', 'author', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
    ]
